### ISSUE TITLE
In appropriate tableview cell sizing, as well as resize all labels so that the UI becomes good.

### ISSUE THREAD

**Issue by gokulnair2001** [TeamRocketCooking/BasicRecipes#23]
Make tableview cells height proper.

**Comment by gokulnair2001** [comment]
#26 I had made changes as required, this changes won't affect your app's performance.

**Comment by Yarostza** [comment]
Oh, we are actively working on our app right now. Please wait on the edits to avoid merge conflicts, but thank you!

**Comment by gokulnair2001** [comment]
Its ok...eager to help you to improve your app:)

**Comment by Yarostza** [comment]
We appreciate the help! Thank you!
